# Generated by Django 5.0.2 on 2024-03-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Timefrom',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Timeto',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
