# Generated by Django 5.0.2 on 2024-03-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0002_profiledb_mobile_alter_profiledb_timefrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
