# Generated by Django 5.0.2 on 2024-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0003_profiledb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('PickupLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('DestinationLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
