# Generated by Django 5.0.2 on 2024-03-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0004_taxibooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxibooking',
            name='Driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driverapp.profiledb'),
        ),
    ]
