# Generated by Django 5.0.2 on 2024-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0005_taxibooking_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxibooking',
            name='Driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
