# Generated by Django 5.0.2 on 2024-03-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0008_alter_taxibooking_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledb',
            name='LastName',
        ),
    ]
