# Generated by Django 5.0.2 on 2024-02-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDb',
        ),
    ]
