# Generated by Django 5.0.2 on 2024-03-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
