# Generated by Django 5.0.2 on 2024-03-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_billingdetails_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.cartitem'),
        ),
    ]
