# Generated by Django 5.0.2 on 2024-03-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_alter_billingdetails_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='billing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.billingdetails'),
        ),
    ]
