# Generated by Django 5.0.2 on 2024-03-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_remove_billingdetails_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='billing_details',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.cartitem'),
        ),
    ]
