# Generated by Django 5.0.2 on 2024-03-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_alter_billingdetails_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='paymentid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
