# Generated by Django 5.0.2 on 2024-03-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_billingdetails_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='paymentid',
        ),
    ]
