# Generated by Django 5.0.2 on 2024-03-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hosapp.appointment')),
                ('prescription', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
