# Generated by Django 5.0.2 on 2024-03-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0003_prescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
