# Generated by Django 5.0.2 on 2024-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0008_prescription_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
