# Generated by Django 5.0.2 on 2024-03-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0009_prescription_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='payment_status',
        ),
    ]
