# Generated by Django 5.0.2 on 2024-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0010_remove_prescription_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
