# Generated by Django 5.0.2 on 2024-03-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='StoreName',
            new_name='Category',
        ),
    ]
